apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-file-handler App
name: opal-file-handler
home: https://github.com/hmcts/opal-file-handler
version: 0.0.19
maintainers:
  - name: HMCTS opal team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
